-- =====================================================================
-- 03 - SILVER: cleaned, standardised, de-duplicated entities
-- Rebuilt from BRONZE on every run (CREATE OR REPLACE ... AS SELECT).
-- =====================================================================

CREATE OR REPLACE TABLE SILVER.DIM_FUND AS
SELECT DISTINCT
    TRIM(FUND_ID)                AS FUND_ID,
    TRIM(FUND_NAME)              AS FUND_NAME,
    INITCAP(TRIM(STRATEGY))      AS STRATEGY,
    VINTAGE_YEAR,
    UPPER(TRIM(CURRENCY))        AS CURRENCY,
    COMMITTED_CAPITAL
FROM BRONZE.EFRONT_FUNDS_RAW;

CREATE OR REPLACE TABLE SILVER.DIM_PORTFOLIO_COMPANY AS
SELECT
    INVESTMENT_ID, FUND_ID, COMPANY_NAME, SECTOR, COUNTRY_CODE,
    INVESTMENT_DATE, INVESTED_AMOUNT, STATUS
FROM (
    SELECT
        TRIM(INVESTMENT_ID)          AS INVESTMENT_ID,
        TRIM(FUND_ID)                AS FUND_ID,
        TRIM(COMPANY_NAME)           AS COMPANY_NAME,
        INITCAP(TRIM(SECTOR))        AS SECTOR,
        UPPER(TRIM(COUNTRY_CODE))    AS COUNTRY_CODE,
        INVESTMENT_DATE,
        INVESTED_AMOUNT,
        INITCAP(TRIM(STATUS))        AS STATUS,
        ROW_NUMBER() OVER (PARTITION BY TRIM(INVESTMENT_ID) ORDER BY LOADED_AT DESC) AS RN
    FROM BRONZE.EFRONT_INVESTMENTS_RAW
)
WHERE RN = 1;

CREATE OR REPLACE TABLE SILVER.FACT_VALUATION AS
SELECT DISTINCT
    TRIM(VALUATION_ID)           AS VALUATION_ID,
    TRIM(INVESTMENT_ID)          AS INVESTMENT_ID,
    VALUATION_DATE,
    FAIR_VALUE,
    UPPER(TRIM(CURRENCY))        AS CURRENCY
FROM BRONZE.CHRONOGRAPH_VALUATIONS_RAW;
