-- =====================================================================
-- Check the demo data in Snowsight (not run by the pipeline)
-- For PROD, replace _TEST with _PROD everywhere.
-- =====================================================================

USE ROLE SYSADMIN;
USE DATABASE TEST_CICD_DEMO_TEST;
USE WAREHOUSE TEST_CICD_DEMO_TEST_WH;

-- 1. Row counts per layer (expected: 4, 11, 20 in BRONZE; 4, 10, 20 in SILVER)
SELECT 'BRONZE.EFRONT_FUNDS_RAW'           AS TABLE_NAME, COUNT(*) AS ROWS_LOADED FROM BRONZE.EFRONT_FUNDS_RAW
UNION ALL SELECT 'BRONZE.EFRONT_INVESTMENTS_RAW',      COUNT(*) FROM BRONZE.EFRONT_INVESTMENTS_RAW
UNION ALL SELECT 'BRONZE.CHRONOGRAPH_VALUATIONS_RAW',  COUNT(*) FROM BRONZE.CHRONOGRAPH_VALUATIONS_RAW
UNION ALL SELECT 'SILVER.DIM_FUND',                    COUNT(*) FROM SILVER.DIM_FUND
UNION ALL SELECT 'SILVER.DIM_PORTFOLIO_COMPANY',       COUNT(*) FROM SILVER.DIM_PORTFOLIO_COMPANY
UNION ALL SELECT 'SILVER.FACT_VALUATION',              COUNT(*) FROM SILVER.FACT_VALUATION;

-- 2. BRONZE (messy) versus SILVER (clean)
SELECT FUND_NAME, STRATEGY, CURRENCY FROM BRONZE.EFRONT_FUNDS_RAW ORDER BY FUND_ID;
SELECT FUND_NAME, STRATEGY, CURRENCY FROM SILVER.DIM_FUND ORDER BY FUND_ID;

-- 3. GOLD views for reporting
SELECT * FROM GOLD.V_FUND_PERFORMANCE ORDER BY FUND_NAME;
SELECT * FROM GOLD.V_SECTOR_EXPOSURE ORDER BY TOTAL_FAIR_VALUE DESC;
SELECT * FROM GOLD.V_INVESTMENT_LATEST_VALUE ORDER BY MOIC DESC;

-- 4. Security: the ANALYST role reads GOLD but not BRONZE
--    (first grant the role to yourself: USE ROLE SECURITYADMIN;
--     GRANT ROLE TEST_CICD_DEMO_TEST_ANALYST TO USER <YOUR_SNOWFLAKE_USER>;)
USE ROLE TEST_CICD_DEMO_TEST_ANALYST;
USE WAREHOUSE TEST_CICD_DEMO_TEST_WH;
SELECT * FROM TEST_CICD_DEMO_TEST.GOLD.V_FUND_PERFORMANCE;     -- works
SELECT * FROM TEST_CICD_DEMO_TEST.BRONZE.EFRONT_FUNDS_RAW;     -- fails: no access
